# safelist
branches:
  only:
  - master

language: node_js
node_js:
  - 8.10.0
before_install:
  - cd client
install:
  - npm install
script:
  - npm run build
COVERALLS_REPO_TOKEN:
  - 3Ku4mYpoX9gGPkcshFwFKSbJicPbW2y4v
